# Working directory path
data_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/growth_rates"

# Path to MAG directory
mag_dir: "/mnt/md1200/sbusi/metabolisHMM/data"

# Path to results directory
results_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/growth_rates/results"

# Path to conda environments' directory
env_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/growth_rates/envs"

#Â Path to directory with auxilliary scripts
scripts_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/growth_rates/scripts"

################################
# Prokka
prokka:
    threads: 4

MAFFT:
    threads: 24

IQTREE:
    threads: 4
